### ISSUE TITLE
 ( Edit: Work perfecly !) Doesn't work on Sony A7ii

### ISSUE THREAD

**Issue by French-People** [ma1co/OpenMemories-AppStore#4]
Hello
I try many solutions to Instaler OpenMemories: AppStore but nothing works for me.  Otherwise OpenMemories: Tweak works correctly with installation of PMCA-GUI-v 0.16-win. EXE under win 10. 
Here's the news:

*********************
Using Windows Drivers-MSC, Windows-MTP
Looking for Sony devices

Querying MTP Device
Sony Corporation ILCE-7M2 is a camera in MTP mode

Model: ILCE-7M2
Product Code: XXXXXXXXXX
Serial Number: xxxxxxxx
Firmware Version: 4.00
*********************

Thank you for your incredible work and the time you offer to the whole world:) The French tell you a big thank you!

**Comment by French-People** [comment]
For information The purpose was to test and make a return on  "TimeLapse by Jonasjuffinger ". Is there a solution?

**Comment by French-People** [comment]
Querying MTP device
Sony Corporation ILCE-7M2 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Downloading apk
Starting task
Starting communication
Uploading 0%
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 74, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 256, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 74, in installApp
  File "C:\projects\sony-pmca-re\pmca\installer\__init__.py", line 84, in install
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

**Comment by ma1co** [comment]
pmca-gui starts a webserver on port 4443 and tries to connect to https://127.0.0.1:4443/ . Maybe your firewall is blocking the request? Can you try to (temporarily) disable your firewall?

**Comment by French-People** [comment]
Thank you for your response ! I find the problem, it's with the configuration of the Proxy in my building ! Now it's ok and your work is perfect ! Thank you very much, you are the best ! So work perfecly on A7ii !!!
