### ISSUE TITLE
[REQUEST] is it possible to integrate Slog2/Slog3?

### ISSUE THREAD

**Issue by JanRiter** [ma1co/OpenMemories-AppStore#5]
Hey,
I just want to ask, if it is possible to add an app which allows us to use the Slog picture profile.
I have a Sony Alpha 7 which has no Slog profile installed, I think, that it would be useful to integrate Slog.
Thanks :)

**Comment by ma1co** [comment]
There is already an open issue for that: https://github.com/ma1co/OpenMemories-Tweak/issues/40
