### ISSUE TITLE
https://sony-pmca.appspot.com/ = Error: Server Error The server encountered an error and could not complete your request. Please try again in 30 seconds.

### ISSUE THREAD

**Issue by taylorkirkproductions** [ma1co/OpenMemories-AppStore#9]
Hi there, 

I am having problems opening the links: 
https://sony-pmca.appspot.com/ or https://sony-pmca.appspot.com/apps 
I receive the message  "Error: Server Error The server encountered an error and could not complete your request. Please try again in 30 seconds". and have tried using multiple browsers such as chrome & safari on multiple MAC computers and still cant gain access.

Wanting to change the 29.52 min limit on my Sony A7iii

Would love any help, thanks

**Comment by ma1co** [comment]
The browser plugin method is not supported anymore. Please use the binaries instead.
